title: Learn By Doing
email: kartheek.gummaluri@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: kartheek91
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
