version: '3'
services:
    jekyll:
        image: jekyll/jekyll:4.2.0  # Updated image with Ruby 2.6+ support
        container_name: kartheek91.github.io
        environment:
            - JEKYLL_ENV=docker

        # Work on a single post with incremental build
        # command: jekyll serve --host 0.0.0.0 --drafts --config _config.yml,_config_dev.yml --watch --incremental

        # Add new post - no incremental mode, Jekyll will regenerate dependencies on save
        command: jekyll serve --host 0.0.0.0 --drafts --config _config.yml

        # Work on design - no incremental mode, no drafts, looks like production
        # command: jekyll serve --host 0.0.0.0 --config _config.yml --watch

        volumes:
            - .:/srv/jekyll
            - ./vendor/bundle:/usr/local/bundle

        ports:
            - 4000:4000
